print(" ------------------------------------------------")
print("|                                                |")
print("|    02GoodbyeWorld                              |")
print("|    Name : Anna                                 |")
print("|    Version : 01                                |")
print("|                                                |")
print(" ------------------------------------------------")
print("Hello World")
input("------> Program paused - press enter to continue")
print("Goodbye World")
