print(" ------------------------------------------------")
print("|                                                |")
print("|    01GoodbyeWorld                              |")
print("|    Name : Anna                                 |")
print("|    Version : 01                                |")
print("|                                                |")
print(" ------------------------------------------------")
input("------> Program paused - press enter to continue")
print("Goodbye World")
