print(" ------------------------------------------------")
print("|                                                |")
print("|    01GoodbyeWorld                              |")
print("|    Name : Anna                                 |")
print("|    Version : 01                                |")
print("|                                                |")
print(" ------------------------------------------------")
print('Hello, world!')
print('Goodbye World')
