print(" ------------------------------------------------")
print("|                                                |")
print("|    06whileLoop                                 |")
print("|    Name : Anna                                 |")
print("|    Version : 01                                |")
print("|                                                |")
print(" ------------------------------------------------")
x=input("What is the name of this subject ")
while x!="IST":
      print("Not Correct - try again")
      x=input("What is the name of this subject ")
else:
      print("")
      print("")
      print("Congratulations!!")
      print("")
      print("")
      print("")